name: Migrate Garmin CN to Garmin Global

on:
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:      # 允许手动点击运行

env:
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  GARMIN_MIGRATE_NUM: 100
  GARMIN_MIGRATE_START: ${{ vars.GARMIN_MIGRATE_START }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Migrate Garmin CN to Garmin Global
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      - run: yarn migrate_garmin_cn_to_global

      - name: Update Progress Variable
        if: success()
        run: |
          # 1. 计算
          NEXT_START=$((GARMIN_MIGRATE_START + GARMIN_MIGRATE_NUM))
          echo "Calculated NEXT_START: $NEXT_START"

          # 2. 调用 API (增加 Content-Type 声明)
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/GARMIN_MIGRATE_START \
            -d "{\"name\":\"GARMIN_MIGRATE_START\",\"value\":\"$NEXT_START\"}"
            
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Save Garmin Session
